name: Build Java JAR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Installer Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3️⃣ Compiler les fichiers .java
      - name: Compile Java files
        run: |
          mkdir -p bin
          javac -d bin *.java

      # 4️⃣ Créer le fichier JAR
      - name: Create JAR
        run: |
          jar cf OpenCraft.jar -C bin .

      # 5️⃣ Sauvegarder le JAR comme artefact
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: OpenCraft
          path: OpenCraft.jar
